---
- name: create a citus-tutorial directory if it doesn't exist 
  file: path=/var/lib/pgsql state=directory
        mode=0755
        recurse=yes

# Until here we just built the VM and installed Postgresql software.
# we have not created any database yet.

- name: Add a group to assign to the OS user which will be created in the next step
  group: name={{ os_user_for_citus_tutorial }} state=present

- name: Create a user to access and work with the Postgres databases
  user: name={{ os_user_for_citus_tutorial }}
        createhome=yes
        group={{ os_user_for_citus_tutorial }}
        groups=postgres
        home=/home/{{ os_user_for_citus_tutorial }}/
        state=present

- name: Check to see if /home/citus1/.bash_profile exists
  stat: path=/home/citus1/.bash_profile
  register: citus1_bash_profile

- name: Create file /home/citus1/.bash_profile
  file: path=/home/citus1/.bash_profile state=touch
  when: citus1_bash_profile.stat.exists == False

- name: Set file permissions for /home/citus1/.bash_profile
  file: path=/home/citus1/.bash_profile state=file
        owner={{ os_user_for_citus_tutorial }}
        group={{ os_user_for_citus_tutorial }}
  when: citus1_bash_profile.stat.exists == False

- name: Creating authorized key for {{ os_user_for_citus_tutorial }} user
  authorized_key: user={{ os_user_for_citus_tutorial }} key="{{ lookup('file', 'roles/citus1OnPgCentos7_prepare/files/put_into_citus1vm_auth_key') }}"

