---
- name: Adding my usual alias shortcuts to .bash_profile of {{ os_user_for_gocd_server }} user
  lineinfile:
    #any spaces around the equals sign while mentioning "dest" fails.
    dest=/home/{{ os_user_for_gocd_server }}/.bash_profile
    line="alias {{item.alias}}='{{item.command}}'"
  with_items:
    - {alias: l, command: 'ls -ltrh'}
    - {alias: eb, command: 'vi ~/.bash_profile'}

- name: Copy over the scripts onto the vm, for later use
  copy: src=replaceCruiseConfigXmlFile.sh
        dest={{ gouser_home_folder }}
        owner={{ os_user_for_gocd_server }}
        group={{ os_user_for_gocd_server }}
        mode=750

- name: Generate passwordfile required for goserver access
  shell: echo "admin:`python -c "import base64;import hashlib; print base64.b64encode(hashlib.sha1('{{ goserver_admin_password }}').digest())"`" > {{ gocd_admin_sha_passwordfile }}

- name: Replace line 2 in cruise config xml file
  shell: "{{ shellscript_to_reconfig_xml }}"

- name: Insert the sha1 file name into the cruise-config.xml
  lineinfile:
    dest={{ gocd_cruise_config_location }}
    line='{{ item }}'
    insertbefore="</cruise>"
  with_items:
    - '  <security>'
    - '    <passwordFile path="{{ gocd_admin_sha_passwordfile }}" />'
    - '  </security>'
    - '</server>'
    - '<agents>'
    - '    <agent hostname="citus1OnPgCentos7" ipaddress="192.168.56.12" uuid="d8a04b77-1fcf-4c4b-96d8-f19a6025a18e" />'
    - '    <agent hostname="mysqlOnCentos7" ipaddress="192.168.56.11" uuid="4c07711c-3440-4e95-b2dd-af182550d961" />'
    - '    <agent hostname="postgresqlOnCentos7" ipaddress="192.168.56.10" uuid="3c450842-652b-4e50-8064-68add19956bb" />'
    - '</agents>'

- name: Creating authorized key for {{ os_user_for_gocd_server }} user
  authorized_key: user={{ os_user_for_gocd_server }} key="{{ lookup('file', 'roles/citus1OnPgCentos7_prepare/files/put_into_citus1vm_auth_key') }}"


