---
- name: Add a group to assign to the OS user which will be created in the next step
  group: name={{ os_user_for_gocd_agent }} state=present

- name: fix the {{ os_user_for_gocd_agent }} user
  user: name={{ os_user_for_gocd_agent }}
        createhome=yes
        group={{ os_user_for_gocd_agent }}
        groups={{ os_user_for_gocd_agent }}
        home=/home/{{ os_user_for_gocd_agent }}/
        state=present

- name: Create directory /var/{{ os_user_for_gocd_agent }}, because while installing go it checks for the existence of this folder
  file: path={{ item }}
        state=directory
        owner={{ os_user_for_gocd_agent }}
        mode=0755
  with_items:
    - /var/{{ os_user_for_gocd_agent }}

- name: Creating authorized key for {{ os_user_for_gocd_agent }} user
  authorized_key: user={{ os_user_for_gocd_agent }} key="{{ lookup('file', 'roles/citus1OnPgCentos7_prepare/files/put_into_citus1vm_auth_key') }}"

- name: Copy over the scripts onto the vm, for later use
  copy: src=gocd_agent_installer.sh
        mode=750
        dest=/home/{{ os_user_for_gocd_agent }}/.

- name: Install GoCD agent
  command: sudo /home/{{ os_user_for_gocd_agent }}/gocd_agent_installer.sh

- name: Replacing the line in the /etc/default/go-agent file to configure the right gocd_server ipaddress
  lineinfile:
    dest=/etc/default/go-agent
    regexp='GO_SERVER_URL=https://127.0.0.1:8154/go'
    line="GO_SERVER_URL=https://{{ gocd_server_ip }}:{{ gocd_server_listen_port2 }}/go"
    state=present
    backrefs=yes

- name: Restarting go-agent to reflect changes in go-agent config to identify the server
  service: name=go-agent state=restarted


