---
- name: Add a group to assign to the OS user which will be created in the next step
  group: name=go state=present

- name: fix the go user
  user: name=go
        createhome=yes
        group=go
        groups=go
        home=/home/go/
        state=present

- name: Create directory /var/go, because while installing go it checks for the existence of this folder
  file: path={{ item }}
        state=directory
        owner=go
        mode=0755
  with_items:
    - /var/go

- name: Using github url as authorized key source for go user
  authorized_key: user=go
        key=https://raw.githubusercontent.com/harshaskm/centos7vm/master/filesForVMs/put_into_citus1vm_auth_key

- name: Copy over the scripts onto the vm, for later use
  copy: src=gocd_agent_installer.sh
        mode=750
        dest=/home/go/.

- name: Install GoCD agent
  command: sudo /home/go/gocd_agent_installer.sh

- name: Replacing the line in the /etc/default/go-agent file to configure the right gocd_server ipaddress
  lineinfile:
    dest=/etc/default/go-agent
    regexp='GO_SERVER_URL=https://127.0.0.1:8154/go'
    line="GO_SERVER_URL=https://{{ gocd_server_ip }}:{{ gocd_server_listen_port2 }}/go"
    state=present
    backrefs=yes

- name: Restarting go-agent to reflect changes in go-agent config to identify the server
  service: name=go-agent state=restarted


