---
- name: Ensure bash, OpenSSL, and libssl are the latest versions
  yum: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
  tags: packages

- name: Copy over the scripts onto the vm, for later use
  copy: src=gocd_server_installer.sh
        mode=750
        dest=.

- name: Create directory /var/go, because while installing go it checks for the existence of this folder
  file: path=/var/go
        state=directory
        mode=0755

- name: Install GoCD server
  command: sudo ./gocd_server_installer.sh





