---
- name: Create a PostgreSQL DB server
  hosts: dbserver
  sudo: yes
  sudo_user: root
  remote_user: root
  vars_files:
    - vars/main.yml

  roles:
  - createdb

- name: CitusData tutorial
  hosts: dbserver
  sudo: yes
  sudo_user: root
  remote_user: postgres

  roles:
  - citusdatatutorial

