---
- name: Ensure bash, OpenSSL, and libssl are the latest versions
  yum: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
#    - libssl-dev
#    - libssl-doc
  tags: packages

#- name: Install PostgreSQL
#  yum: name={{ item }} update_cache=true state=installed
#  with_items:
#    - postgresql
#    - postgresql-contrib
#    - libpq-dev
#    - python-psycopg1
#  tags: packages
#
#- name: Ensure the PostgreSQL service is running
#  service: name=postgresql state=started enabled=yes
#
#- name: Ensure database is created
#  sudo_user: postgres
#  postgresql_db: name={{ db_name }}
#                 encoding='UTF-8'
#                 lc_collate='en_US.UTF-8'
#                 lc_ctype='en_US.UTF-8'
#                 template='template-0'
#                 state=present
#
#- name: Ensure user has access to the database
#  sudo_user: postgres
#  postgresql_user: db={{ db_name }}
#                   name={{ db_user }}
#                   password={{ db_password }}
#                   priv=ALL
#                   state=present
#
#- name: Ensure user does not have unnecessary privileges
#  sudo_user: postgres
#  postgresql_user: name{{ db_user }}
#                   role_attr_flags=NOSUPER,NOCREATEDB
#                   state=pr

- name: For Base "Add a line with the text to the yum repo file if it does not exist"
  lineinfile: >
    dest=/etc/yum.repos.d/CentOS-Base.repo
    insertafter="Base"
    line="exclude=postgresql*"
  tags: modifyYumFile

- name: For Updates "Add a line with the text to the yum repo file if it does not exist"
  lineinfile: >
    dest=/etc/yum.repos.d/CentOS-Base.repo
    insertafter="Updates"
    line=" exclude=postgresql*"
  tags: modifyYumFile

- name: install postgres yum repo from http://yum.postgresql.org/repopackages.php#pg95 (for version 9.5)
  yum: name=https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm state=present
  tags: installYumRepoForPostgres

- name: install Postgres9.5 server
  yum: name=postgresql95-server state=present
  tags: installPostgresServer95

- name: Enable the postgres db service (this is equivalent to chkconfig on)
  command: systemctl enable postgresql-9.5
  tags: enablePosgresService

- stat: path=/path/to/something
  register: p
  when: p.stat.isdir is defined and p.stat.isdir
- debug: msg="Path exists and is a directory"

- name: This is to initialize the settings that are required for the db to started and function.
  command: /usr/pgsql-9.5/bin/postgresql95-setup initdb
  when: p.stat.isdir is not defined and not p.stat.isdir
  tags: initdb

- name: Start the database service
  command: sudo systemctl start postgresql-9.5.service








