---
- name: Ensure bash, OpenSSL, and libssl are the latest versions
  yum: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
  tags: packages

- name: Add a group to assign to the OS user which will be created in the next step
  group: name={{ os_user_for_gocd_server }} state=present

- name: Create a user to access and work with the Postgres databases
  user: name={{ os_user_for_gocd_server }}
        createhome=yes
        group={{ os_user_for_gocd_server }}
        home=/home/{{ os_user_for_gocd_server }}/
        state=present

- name: Using github url as authorized key source for {{ os_user_for_gocd_server }} user
  authorized_key: user={{ os_user_for_gocd_server }} key=https://raw.githubusercontent.com/harshaskm/centos7vm/master/filesForVMs/put_into_citus1vm_auth_key





