---
- name: Ensure bash, OpenSSL, and libssl are the latest versions
  yum: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
#    - libssl-dev
#    - libssl-doc
  tags: packages

- name: For Base "Add a line with the text to the yum repo file if it does not exist"
  lineinfile: >
    dest=/etc/yum.repos.d/CentOS-Base.repo
    insertafter="Base"
    line="exclude=postgresql*"
  tags: modifyYumFile

- name: For Updates "Add a line with the text to the yum repo file if it does not exist"
  lineinfile: >
    dest=/etc/yum.repos.d/CentOS-Base.repo
    insertafter="Updates"
    line=" exclude=postgresql*"
  tags: modifyYumFile

- name: install postgres yum repo from http://yum.postgresql.org/repopackages.php#pg95 (for version 9.5)
  yum: name=https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm state=present
  tags: installYumRepoForPostgres

- name: install Postgres9.5 server
  yum: name=postgresql95-server state=present
  tags: installPostgresServer95

- name: create a citus-tutorial directory if it doesn't exist 
  file: path=/var/lib/pgsql state=directory
        mode=0755
        recurse=yes

- name: Enable the postgres db service (this is equivalent to chkconfig on)
  command: systemctl enable postgresql-9.5
  tags: enablePosgresService

# Until here we just built the VM and installed Postgresql software.
# we have not created any database yet.

- name: Add a group to assign to the OS user which will be created in the next step
  group: name=citus1 state=present

- name: Create a user to access and work with the Postgres databases
  user: name=citus1
        createhome=yes
        group=citus1
        groups=postgres
        home=/home/citus1/
        state=present

- name: Using github url as authorized key source for citus1 user
  authorized_key: user=citus1 key=https://raw.githubusercontent.com/harshaskm/centos7vm/master/filesForVMs/put_into_citus1vm_auth_key





