---
os_user_for_gocd_server: go
goserver_admin_username: admin
goserver_admin_password: password#123
gocd_admin_sha_passwordfile: /home/go/gocd_admin_sha_passwordfile
gocd_cruise_config_location: /etc/go/cruise-config.xml
