---
- name: Create a PostgreSQL DB server
  hosts: citusdata_dbserver
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - vars/main.yml

  roles:
  - installPostgres
  - citus1OnPgCentos7_prepare


- name: CitusData tutorial
  hosts: citusdata_dbserver
  become: yes
  become_method: sudo
  become_user: citus1

  roles:
  - citus1OnPgCentos7_install
