---
- name: Create a GoCD server
  hosts: gocd_server_asVagrant
  become: yes
  become_user: root

  roles:
  - gocdOnCentos7_install


- name: Configure GoCD server
  hosts: gocd_server_asVagrant
  become: yes
  become_user: go

  roles:
  - gocdOnCentos7_prepare

