---
- name: Create a MySql DB server
  hosts: mysqlOnCentos7_dbserver_asVagrant
  sudo: yes
  sudo_user: root
  remote_user: root
  vars_files:
    - vars/main.yml

  roles:
  - mysqlOnCentos7_createdb

