---
- name: Create a MySql DB server
  hosts: mysqlOnCentos7_dbserver_asVagrant
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - vars/main.yml

  roles:
  - mysqlOnCentos7_createdb
