---
- name: Create a PostgreSQL DB server
  hosts: postgresqlOnCentos7
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - vars/main.yml

  roles:
  - installPostgres
  - postgresqlOnCentos7_createdb

