---
- name: Create a PostgreSQL DB server
  hosts: postgresqlOnCentos7
  sudo: yes
  sudo_user: root
  remote_user: root
  vars_files:
    - vars/main.yml

  roles:
  - installPostgres
  - postgresqlOnCentos7_createdb

